Add seek preview as a configurable option
bitmovin/bitmovin-player-ui pull request #412
Opened 2021-11-03 23:22 UTC by huysbs

2022-02-11 10:16 UTC, stonko1994 requested changes
Sorry for the late review.

- Can you please add a PR description to describe the problem and the change in this PR? Also, screenshots of how the UI looks when the option is disabled would be helpful.
- Is the intention only hiding the thumbnails or the whole `SeekBarLabel` (including the time) as well?
- I run the playback locally and changing the option doesn't seem to have any effect as it is right now 🤔 
- Also please resolve the merge conflicts.

2022-02-11 10:16 UTC, stonko1994 commented on src/ts/uiconfig.ts
> +  enableSeekPreview?: boolean;
Any specific reason to but the option on the `UIConfig` over the `SeekBarConfig` 🤔

2022-02-12 02:41 UTC, huysbs commented
> * Can you please add a PR description to describe the problem and the change in this PR? Also, screenshots of how the UI looks when the option is disabled would be helpful.
> * Is the intention only hiding the thumbnails or the whole `SeekBarLabel` (including the time) as well?
> * I run the playback locally and changing the option doesn't seem to have any effect as it is right now 🤔
> * Also please resolve the merge conflicts.

I've updated the description. A screenshot would not be useful in this case. When you disable the seekPreview what happens is that the actual video will not update as you drag the seek button around. The Seek Preview is not the thumbnail above the mouse but it's preview the actual video stream.

2022-02-15 09:42 UTC, stonko1994 commented
Thanks for adding the description 👍 The target of this PR is clear to me now.

I'm still undecided if the new config option should go to the `UIConfig` or to the `SeekBarConfig`. The reasoning is that the `Seekbar` actually is reused e.g. for the `VolumeSlider`. There we also have an `onSeekPreview` with an `update...WhileScrubbing` which is not configurable by this property now.
One could argue that this is unrelated but not the best design but still having a config option on every `SeekBar` directly if the value should be updated while scrubbing or after releasing would IMO the cleaner approach.

For convenience, we could keep the option on the `UIConfig`. See `seekbarSnappingRange` as an example:
https://github.com/bitmovin/bitmovin-player-ui/blob/3d25d3304acaac0b4d14bb4d97d204ef40793929/src/ts/components/seekbar.ts#L420-L422

PS: Please add a changelog entry and resolve the merge conflict.

2022-02-17 04:10 UTC, quochuy commented
@stonko1994 not sure if I needed to bump the version number in package.json or if its automatically done by your publishing process but I did it. If it needs to be reverted, let me know.

2022-02-17 07:30 UTC, stonko1994 commented
> @stonko1994 not sure if I needed to bump the version number in package.json or if its automatically done by your publishing process but I did it. If it needs to be reverted, let me know.

Yes please revert the version bump. That will happen in our release process. Apart from that, looks good to me 👍

2022-02-18 10:52 UTC, felix-hoc requested changes
Thanks a lot for your contribution! The code changes look good to me, just one suggestion for the changelog entry.

Also, some organizational stuff: Please change the base branch to `develop` and make sure the changelog entry is in the correct section. It should be in `## [develop]`, without a date. This will be updated automatically on release. As an example, see this PR: https://github.com/bitmovin/bitmovin-player-ui/pull/425/files#diff-06572a96a58dc510037d5efa622f9bec8519bc1beab13c9f251e97e657a9d4edR6

2022-02-18 10:52 UTC, felix-hoc commented on CHANGELOG.md
> +- seek preview is now configurable via `isSeekPreviewEnabled` from SeekBarConfig or UIConfig
Slight nitpick to aviod confusion about the config options. We should mention the respective property names
```suggestion
- Seek preview is now configurable via `UIConfig.enableSeekPreview` or `SeekBarConfig.isSeekPreviewEnabled`
```

2022-02-22 00:09 UTC, quochuy commented
@felix-hoc I've did the suggested changes. Also renamed SeekBarConfig.isSeekPreviewEnabled to SeekBarConfig.enableSeekPreview it makes more sense since it's a config name not a state (which it initially was).

2022-02-22 07:39 UTC, felix-hoc commented
Great, thanks 🙌🏼 this looks g2g from my side.
Anything from you @stonko1994?

2022-02-22 07:40 UTC, felix-hoc approved these changes

2022-02-23 08:25 UTC, stonko1994 approved these changes
Unit tests would be nice if easily possible but not a hard requirement.

2022-03-01 15:41 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/bitmovin/bitmovin-player-ui?pullRequest=412) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/bitmovin/bitmovin-player-ui?pullRequest=412) before we can accept your contribution.<br/>**1** out of **2** committers have signed the CLA.<br/><br/>:white_check_mark: huysbs<br/>:x: felix-hoc<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/bitmovin/bitmovin-player-ui?pullRequest=412) it.</sub>

2022-03-10 12:19 UTC, merged