[PW-6220] Provide ability to override ListBox aria-labels
bitmovin/bitmovin-player-ui pull request #419
Opened 2021-12-20 12:37 UTC by kishorens

Problem: By default, we are using label/text as `aria-label` for list-item when Listbox is used. When complex HTML is used as a label customer wants to have an option to provide a different value for `aria-label`

Fix: provided an option to pass optional `aria-label` when  `additem` is called for adding new items to the Listbox

2022-01-13 10:03 UTC, TeslaAdis requested changes
Overall looks good.
Missing changelog entry.

Can we also have a unit test when `ariaLabel` is not provided?

2022-01-13 10:13 UTC, TeslaAdis commented on src/ts/components/listselector.ts
> +    const listItem = { key: key, label: i18n.performLocalization(label), ...(ariaLabel && {ariaLabel: ariaLabel})};
```suggestion
    const listItem = { key: key, label: i18n.performLocalization(label), ...(ariaLabel && { ariaLabel })};
```

2022-01-17 06:44 UTC, kishorens commented
> Can we also have a unit test when ariaLabel is not provided?

@TeslaAdis  The existing unit tests already cover the cases where aria labels are not provided. 
```
  it('adds new items to the end of the list', () => {
      listSelector.addItem('A', 'itemA');
      listSelector.addItem('C', 'itemC');
      listSelector.addItem('B', 'itemB');

2022-01-18 12:12 UTC, TeslaAdis approved these changes

2022-01-18 12:20 UTC, merged