Disable auto-hide to not require two touches for click-through and skipping ads
bitmovin/bitmovin-player-ui pull request #622
Opened 2024-05-13 13:24 UTC by hawk23

ticket: https://bitmovin.atlassian.net/browse/PI-2655

## Description
Currently, when the small-screen ads UI is used on a touch device, two touches are needed to either hit the "skip ad" button or to open the ad  click-through URL. Especially for the "skip ad" button this is a confusing user experience as it is always visible and one touch should be sufficient to tap it.

To fix this, the auto hide is disabled for the small screen ads UI. After this change, the "skip ad" button can be triggered with a single touch. The same holds for triggering the ad click through URL.

## Checklist (for PR submitter and reviewers)
- [ ] `CHANGELOG` entry

2024-05-14 12:12 UTC, rolandkakonyi approved these changes
Manual testing works as expected!

2024-05-15 09:22 UTC, felix-hoc approved these changes

2024-05-15 10:05 UTC, felix-hoc requested changes
As discussed offline:
On Web, this causes the black shadow and fullscreen button to be visible during ad playback, which I think we don't want... Would be great if we could find a solution to make the Ad controls independent of the rest of the UI controls (but not sure how to do that 😅 )
![Screenshot 2024-05-15 at 12 03 49](https://github.com/bitmovin/bitmovin-player-ui/assets/16101788/93d0d245-2436-4894-8bad-e125eef98d25)

2024-05-16 14:30 UTC, closed without merging

2024-05-16 14:54 UTC, hawk23 commented
> As discussed offline: On Web, this causes the black shadow and fullscreen button to be visible during ad playback, which I think we don't want... Would be great if we could find a solution to make the Ad controls independent of the rest of the UI controls (but not sure how to do that 😅 )

An approach that still allows for auto hiding the control bar is now implemented in [this PR](https://github.com/bitmovin/bitmovin-player-ui/pull/624) (still Draft).