Remaining time in ad break duration
bitmovin/bitmovin-player-ui pull request #640
Opened 2024-08-06 02:01 UTC by saravanans-github

## Description
added support for a new adMessagePlaceholder - `adBreakRemainingTime`. This placeholder displays the remaining time in an ad break.

## Checklist (for PR submitter and reviewers)
- code loops through all remaining linearAds in an ad break and adds to the time left in the current ad to compute this value
- [ ] `CHANGELOG` entry

2024-08-06 07:42 UTC, dweinber commented on src/ts/stringutils.ts
> +          let duration = durations.slice(indexOfActiveAd).reduce((prev, current) => prev + current, 0);
This could be simplified like this (unless I'm missing something):

```suggestion
          const duration = player.ads.getActiveAdBreak().ads
            .map(ad => ad.duration)
            .reduce((prev, current) => prev + current, 0);
```

2024-08-06 07:43 UTC, dweinber commented on src/ts/stringutils.ts
> +      '\\{(remainingTime|playedTime|adDuration|adBreakRemainingTime)(}|%((0[1-9]\\d*(\\.\\d+(d|f)|d|f)|\\.\\d+f|d|f)|hh:mm:ss|mm:ss)})',
Please add the new placeholder also to the documentation of the function (line 73/74)

2024-08-12 06:05 UTC, saravanans-github commented on src/ts/stringutils.ts
> +          let duration = durations.slice(indexOfActiveAd).reduce((prev, current) => prev + current, 0);
thanks @dweinber . I've simplified the code per your guidance.

2024-08-12 06:05 UTC, saravanans-github commented on src/ts/stringutils.ts
> +      '\\{(remainingTime|playedTime|adDuration|adBreakRemainingTime)(}|%((0[1-9]\\d*(\\.\\d+(d|f)|d|f)|\\.\\d+f|d|f)|hh:mm:ss|mm:ss)})',
thank you. added to the function documentation and provided an example too.

2024-08-13 09:19 UTC, felix-hoc commented
@saravanans-github please do not alter the PR Checklist - it should stay as-is, because it contains the formal PR requirements. Your changes should be described separately.

Please re-add it, and add a Changelog entry :)

2024-08-19 11:18 UTC, saravanans-github commented
thank you @felix-hoc; I've made the change to the PR checklist. Kindly see if that suffices please?

2024-08-19 11:35 UTC, felix-hoc commented
@saravanans-github the CI is still failing. Also, your branch is quite a bit behind `main`, please pull it in and resolve any conflicts :)

2024-08-19 12:10 UTC, felix-hoc requested changes
The code looks good, just some nit picks from my side.

Please ensure:
- your branch is up-to-date with `main`
- there are no conflicts
- the CI passes and the code is properly formatted (your IDE should highlight formatting errors that are identified by TSLint and offer to auto-fix them)
- you add a changelog entry

2024-08-19 12:10 UTC, felix-hoc commented on src/ts/stringutils.ts
> +            .reduce((prev, current) => prev + current, 0);
nit: this could be simplified to use a single `reduce`:

```suggestion
          const duration = player.ads.getActiveAdBreak().ads
	    .slice(indexOfActiveAd)
            .reduce((total, ad) => total + (ad.isLinear ? (ad as LinearAd).duration : 0), 0);
```

2024-08-19 12:10 UTC, felix-hoc commented on src/ts/stringutils.ts
> +      } else if (formatString.indexOf('adBreakRemainingTime') > -1) { // To display the remaining time in the ad bread as opposed to in the ad
typo
```suggestion
      } else if (formatString.indexOf('adBreakRemainingTime') > -1) { // To display the remaining time in the ad break as opposed to in the ad
```

2024-08-21 06:04 UTC, felix-hoc requested changes

2024-08-21 06:04 UTC, felix-hoc commented on CHANGELOG.md
> +## [3.70.0] - 2024-08-21
As this is not yet released, the section should be named `Unreleased` and there should not be any date. See http://keepachangelog.com/

```suggestion
## [Unreleased]
```

2024-08-21 06:04 UTC, felix-hoc commented on CHANGELOG.md
> +- Support for a new adMessagePlaceholder `adBreakRemainingTime` in [AdMessageLabel](https://cdn.bitmovin.com/player/ui/3/docs/classes/AdMessageLabel.html). It displays the remaining time in an ad bre
nit
```suggestion
- Support for a new placeholder `{adBreakRemainingTime}` in [AdMessageLabel](https://cdn.bitmovin.com/player/ui/3/docs/classes/AdMessageLabel.html) that displays the remaining time in an ad break. [Documentation](https://cdn.bitmovin.com/player/ui/3/docs/functions/StringUtils.replaceAdMessagePlaceholders.html) on usage.
```

2024-08-21 07:09 UTC, felix-hoc approved these changes
Very nice! 😃

2024-08-21 14:37 UTC, merged